apiVersion: v1
kind: Secret
metadata:
  name: finrecon-secrets
  labels:
    {{- include "finrecon.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secrets.dbConnectionString | quote }}
  RabbitMQ__Host: {{ .Values.secrets.rabbitMQHost | quote }}
  RabbitMQ__Username: {{ .Values.secrets.rabbitMQUsername | quote }}
  RabbitMQ__Password: {{ .Values.secrets.rabbitMQPassword | quote }}
  MinIO__Endpoint: {{ .Values.secrets.minioEndpoint | quote }}
  MinIO__AccessKey: {{ .Values.secrets.minioAccessKey | quote }}
  MinIO__SecretKey: {{ .Values.secrets.minioSecretKey | quote }}
  Jwt__Secret: {{ .Values.secrets.jwtSecret | quote }}
